insert into corps (CorpsID, CorpsName, Specialization) values (1, 'Bahad 14', 'Strategic Intel Command');
insert into corps (CorpsID, CorpsName, Specialization) values (2, 'Unit 81', 'Strategic Supplies Stock');
insert into corps (CorpsID, CorpsName, Specialization) values (3, 'Northern Engineering Battalion', 'Data Encryption');
insert into corps (CorpsID, CorpsName, Specialization) values (4, 'Navy Technical School', 'Malware Analysis');
insert into corps (CorpsID, CorpsName, Specialization) values (5, 'Bahad 88', 'Fuel Logistics');
insert into corps (CorpsID, CorpsName, Specialization) values (6, 'Warfare Doctrine Unit', 'Urban Intelligence');
insert into corps (CorpsID, CorpsName, Specialization) values (7, 'Air Force', 'Supply Planning');
insert into corps (CorpsID, CorpsName, Specialization) values (8, 'Airborne Radar Unit', 'Training Curriculum Design');
insert into corps (CorpsID, CorpsName, Specialization) values (9, 'Strategic Logistics Base', 'Refresher Combat Training.');
insert into corps (CorpsID, CorpsName, Specialization) values (10, 'Bahad 48', 'Heavy Vehicle Logistics');
insert into corps (CorpsID, CorpsName, Specialization) values (11, 'Logistics Corps', 'Rescue and Recovery');
insert into corps (CorpsID, CorpsName, Specialization) values (12, 'Navy', 'Combat Fitness');
insert into corps (CorpsID, CorpsName, Specialization) values (13, 'Bahad 61', 'Recruitment Strategy');
insert into corps (CorpsID, CorpsName, Specialization) values (14, 'Bahad 27', 'Counterterrorism');
insert into corps (CorpsID, CorpsName, Specialization) values (15, 'Air Force', 'Tank Operations');
insert into corps (CorpsID, CorpsName, Specialization) values (16, 'Field Observers Unit', 'Firefighting Rescue');
insert into corps (CorpsID, CorpsName, Specialization) values (17, 'Bahad 94', 'Performance Music');
insert into corps (CorpsID, CorpsName, Specialization) values (18, 'UAV Control School', 'Naval Warfare');
insert into corps (CorpsID, CorpsName, Specialization) values (19, 'Bahad 28', 'Border Surveillance');
insert into corps (CorpsID, CorpsName, Specialization) values (20, 'Bahad 8', 'Air Photo Interpretation');
insert into corps (CorpsID, CorpsName, Specialization) values (21, 'Bahad 80', 'Target Acquisition');
insert into corps (CorpsID, CorpsName, Specialization) values (22, 'Iron Dome Battalion', 'Helicopter Piloting');
insert into corps (CorpsID, CorpsName, Specialization) values (23, 'Air Force', 'Undercover Operations');
insert into corps (CorpsID, CorpsName, Specialization) values (24, 'Bahad 23', 'Surveillance Analytics');
insert into corps (CorpsID, CorpsName, Specialization) values (25, 'Bahad 13', 'Missile Interception');
insert into corps (CorpsID, CorpsName, Specialization) values (26, 'Reserve Administration', 'Data Security Policy');
insert into corps (CorpsID, CorpsName, Specialization) values (27, 'Communications School', 'Tactical Navigation');
insert into corps (CorpsID, CorpsName, Specialization) values (28, 'Bahad 43', 'Military Networking');
insert into corps (CorpsID, CorpsName, Specialization) values (29, 'Bahad 36', 'HR Metrics');
insert into corps (CorpsID, CorpsName, Specialization) values (30, 'Advanced Weapons Unit', 'Naval Assault');
insert into corps (CorpsID, CorpsName, Specialization) values (31, 'Nahal Brigade', 'E-Learning Development');
insert into corps (CorpsID, CorpsName, Specialization) values (32, 'Logistics Planning Division', 'Music Instruction');
insert into corps (CorpsID, CorpsName, Specialization) values (33, 'Satellite Intelligence Unit', 'High-Altitude Recon');
insert into corps (CorpsID, CorpsName, Specialization) values (34, 'Warfare Simulation Unit', 'Artillery Targeting');
insert into corps (CorpsID, CorpsName, Specialization) values (35, 'Bahad 85', 'Combat Sim Strategy');
insert into corps (CorpsID, CorpsName, Specialization) values (36, 'Bahad 49', 'Communications Tower Setup');
insert into corps (CorpsID, CorpsName, Specialization) values (37, 'Iron Dome Battalion', 'Logistical Operations');
insert into corps (CorpsID, CorpsName, Specialization) values (38, 'Rocket Launcher Unit', 'Command Structure Systems');
insert into corps (CorpsID, CorpsName, Specialization) values (39, 'Anti-Aircraft Unit', 'UAV Assembly');
insert into corps (CorpsID, CorpsName, Specialization) values (40, 'Bahad 41', 'Reserve Kit Distribution');
insert into corps (CorpsID, CorpsName, Specialization) values (41, 'Military Police Corps', 'Mechanical Maintenance');
insert into corps (CorpsID, CorpsName, Specialization) values (42, 'Armored Recovery Unit', 'Mobile Surgery Coordination');
insert into corps (CorpsID, CorpsName, Specialization) values (43, 'Golani Brigade', 'Target Acquisition');
insert into corps (CorpsID, CorpsName, Specialization) values (44, 'Bahad 91', 'Satellite Comm Tracking');
insert into corps (CorpsID, CorpsName, Specialization) values (45, 'Kfir Brigade', 'Tactical Software');
insert into corps (CorpsID, CorpsName, Specialization) values (46, 'Bahad 59', 'Code Analysis');
insert into corps (CorpsID, CorpsName, Specialization) values (47, 'Weather Unit', 'Explosive Disposal');
insert into corps (CorpsID, CorpsName, Specialization) values (48, 'Bahad 84', 'Equipment Allocation');
insert into corps (CorpsID, CorpsName, Specialization) values (49, 'Bahad 61', 'Desert Combat');
insert into corps (CorpsID, CorpsName, Specialization) values (50, 'David’s Sling Unit', 'Tank Command');
insert into corps (CorpsID, CorpsName, Specialization) values (51, 'Bahad 58', 'Budget Management');
insert into corps (CorpsID, CorpsName, Specialization) values (52, 'Coastal Defense Unit', 'Radar Monitoring');
insert into corps (CorpsID, CorpsName, Specialization) values (53, 'C2 Systems Unit', 'Cyber Curriculum');
insert into corps (CorpsID, CorpsName, Specialization) values (54, 'Military Cyber School', 'Radar Installation');
insert into corps (CorpsID, CorpsName, Specialization) values (55, '188th Brigade', 'Soldier Welfare');
insert into corps (CorpsID, CorpsName, Specialization) values (56, 'Bahad 68', 'CBRN Safety');
insert into corps (CorpsID, CorpsName, Specialization) values (57, 'Officer Training Command', 'Reserve Kit Distribution');
insert into corps (CorpsID, CorpsName, Specialization) values (58, 'Military Rabbinate', 'Mobile Medicine');
insert into corps (CorpsID, CorpsName, Specialization) values (59, 'Bahad 84', 'Military Court Procedure');
insert into corps (CorpsID, CorpsName, Specialization) values (60, 'Communications Security Unit', 'Coastal Radar');
insert into corps (CorpsID, CorpsName, Specialization) values (61, 'Bahad 57', 'Drone Control');
insert into corps (CorpsID, CorpsName, Specialization) values (62, 'Intelligence Directorate', 'Canine Handling');
insert into corps (CorpsID, CorpsName, Specialization) values (63, 'Warfare Simulation Unit', 'Combat Sim Strategy');
insert into corps (CorpsID, CorpsName, Specialization) values (64, 'Sayeret Matkal', 'Recon Training');
insert into corps (CorpsID, CorpsName, Specialization) values (65, 'Bahad 17', 'Geo-Intelligence');
insert into corps (CorpsID, CorpsName, Specialization) values (66, 'Bahad 29', 'Reserve Command');
insert into corps (CorpsID, CorpsName, Specialization) values (67, 'IDF Orchestra', 'Religious Support');
insert into corps (CorpsID, CorpsName, Specialization) values (68, 'Bahad 67', 'Systems Logistics');
insert into corps (CorpsID, CorpsName, Specialization) values (69, 'Financial Directorate', 'Equipment Delivery');
insert into corps (CorpsID, CorpsName, Specialization) values (70, 'Bahad 25', 'Counterterrorism');
insert into corps (CorpsID, CorpsName, Specialization) values (71, 'Northern Engineering Battalion', 'Military Law Enforcement');
insert into corps (CorpsID, CorpsName, Specialization) values (72, 'Bahad 10', 'Drone Piloting');
insert into corps (CorpsID, CorpsName, Specialization) values (73, 'Bahad 91', 'Training Curriculum Design');
insert into corps (CorpsID, CorpsName, Specialization) values (74, 'IDF Technological College', 'Armored Vehicle Recovery');
insert into corps (CorpsID, CorpsName, Specialization) values (75, 'Anti-Aircraft Unit', 'Officer Leadership');
insert into corps (CorpsID, CorpsName, Specialization) values (76, 'Egoz Unit', 'Emergency Extraction');
insert into corps (CorpsID, CorpsName, Specialization) values (77, 'Logistics Distribution Center', 'Draft Planning');
insert into corps (CorpsID, CorpsName, Specialization) values (78, 'Bahad 54', 'E-Learning Development');
insert into corps (CorpsID, CorpsName, Specialization) values (79, 'Communications Security Unit', 'Weapon Testing');
insert into corps (CorpsID, CorpsName, Specialization) values (80, 'Anti-Smuggling Unit', 'Morale Assessment');
insert into corps (CorpsID, CorpsName, Specialization) values (81, 'Canine Unit', 'Experimental Testing');
insert into corps (CorpsID, CorpsName, Specialization) values (82, 'IDF Combat Academy', 'Jet Navigation');
insert into corps (CorpsID, CorpsName, Specialization) values (83, 'Nahal Brigade', 'Tactical Supply Drops');
insert into corps (CorpsID, CorpsName, Specialization) values (84, 'Personnel Branch', 'Case Investigations');
insert into corps (CorpsID, CorpsName, Specialization) values (85, 'Northern Command', 'Naval Engineering');
insert into corps (CorpsID, CorpsName, Specialization) values (86, 'Bahad 99', 'Land Unit Strategy');
insert into corps (CorpsID, CorpsName, Specialization) values (87, 'Bahad 36', 'Helicopter Piloting');
insert into corps (CorpsID, CorpsName, Specialization) values (88, 'Training Division', 'Ballistics Simulation');
insert into corps (CorpsID, CorpsName, Specialization) values (89, 'Sea Corps Base', 'Intelligence Briefing');
insert into corps (CorpsID, CorpsName, Specialization) values (90, 'Morale & Culture Unit', 'Cyber Offense');
insert into corps (CorpsID, CorpsName, Specialization) values (91, 'Bahad 95', 'Rapid Deployment Surgery');
insert into corps (CorpsID, CorpsName, Specialization) values (92, 'Bahad 45', 'Battlefield Analysis');
insert into corps (CorpsID, CorpsName, Specialization) values (93, 'Combat Intelligence Collection Corps', 'Intelligence Briefing');
insert into corps (CorpsID, CorpsName, Specialization) values (94, 'Bahad 47', 'Contraband Prevention');
insert into corps (CorpsID, CorpsName, Specialization) values (95, 'Military Archive Unit', 'Airborne Deployment');
insert into corps (CorpsID, CorpsName, Specialization) values (96, 'Technology and Maintenance Corps', 'Fighter Jet Maintenance');
insert into corps (CorpsID, CorpsName, Specialization) values (97, 'Bahad 26', 'Satellite Imaging');
insert into corps (CorpsID, CorpsName, Specialization) values (98, 'Bahad 91', 'Missile Interception');
insert into corps (CorpsID, CorpsName, Specialization) values (99, 'Arrow Missile Unit', 'Satellite Monitoring');
insert into corps (CorpsID, CorpsName, Specialization) values (100, 'Dog Training School', 'Legal Defense');
insert into corps (CorpsID, CorpsName, Specialization) values (101, 'Bahad 78', 'Detention Facility Security');
insert into corps (CorpsID, CorpsName, Specialization) values (102, 'Bahad 32', 'Emergency Medicine');
insert into corps (CorpsID, CorpsName, Specialization) values (103, 'Shayetet 13', 'Weather Forecasting');
insert into corps (CorpsID, CorpsName, Specialization) values (104, 'Bahad 17', 'Officer Leadership');
insert into corps (CorpsID, CorpsName, Specialization) values (105, 'Commando Brigade', 'Recruitment Strategy');
insert into corps (CorpsID, CorpsName, Specialization) values (106, 'Bahad 77', 'Helicopter Piloting');
insert into corps (CorpsID, CorpsName, Specialization) values (107, 'Bahad 64', 'Reserve Kit Distribution');
insert into corps (CorpsID, CorpsName, Specialization) values (108, 'Bahad 11', 'Cyber Curriculum');
insert into corps (CorpsID, CorpsName, Specialization) values (109, 'IDF Spokesperson Unit', 'Weather Forecasting');
insert into corps (CorpsID, CorpsName, Specialization) values (110, 'Academic Officers Program', 'Naval Warfare');
insert into corps (CorpsID, CorpsName, Specialization) values (111, 'Bahad 44', 'Signals Training');
insert into corps (CorpsID, CorpsName, Specialization) values (112, 'Bahad 62', 'Drone Piloting');
insert into corps (CorpsID, CorpsName, Specialization) values (113, 'Bahad 56', 'Weather Forecasting');
insert into corps (CorpsID, CorpsName, Specialization) values (114, 'Planning Directorate', 'Experimental Testing');
insert into corps (CorpsID, CorpsName, Specialization) values (115, 'Education and Youth Corps', 'Aerial Refueling');
insert into corps (CorpsID, CorpsName, Specialization) values (116, 'Military Rabbinate', 'Geo-Political Analysis');
insert into corps (CorpsID, CorpsName, Specialization) values (117, 'IDF Fuel Unit', 'Naval Engineering');
insert into corps (CorpsID, CorpsName, Specialization) values (118, 'Officer School', 'Coastal Surveillance');
insert into corps (CorpsID, CorpsName, Specialization) values (119, 'Bahad 85', 'Airborne Deployment');
insert into corps (CorpsID, CorpsName, Specialization) values (120, 'Air Intelligence Unit', 'Malware Analysis');
insert into corps (CorpsID, CorpsName, Specialization) values (121, 'Bahad 52', 'Drone Control');
insert into corps (CorpsID, CorpsName, Specialization) values (122, 'Tzrifin Base', 'Weapon Testing');
insert into corps (CorpsID, CorpsName, Specialization) values (123, 'Logistics Corps', 'Educational Program Development');
insert into corps (CorpsID, CorpsName, Specialization) values (124, 'Cyber School', 'Educational Program Development');
insert into corps (CorpsID, CorpsName, Specialization) values (125, 'Defensive Cyber Unit', 'Anti-Air Support');
insert into corps (CorpsID, CorpsName, Specialization) values (126, 'Special Operations Command', 'Armored Unit Recovery');
insert into corps (CorpsID, CorpsName, Specialization) values (127, 'Recruitment Administration', 'Border Interception');
insert into corps (CorpsID, CorpsName, Specialization) values (128, 'Transport Squadron', 'Commando Infiltration');
insert into corps (CorpsID, CorpsName, Specialization) values (129, 'Bahad 64', 'Border Patrol');
insert into corps (CorpsID, CorpsName, Specialization) values (130, 'Reserve Administration', 'Missile Guidance');
insert into corps (CorpsID, CorpsName, Specialization) values (131, 'Navy Diving School', 'Naval Warfare');
insert into corps (CorpsID, CorpsName, Specialization) values (132, 'Field Observers Unit', 'Underwater Missions');
insert into corps (CorpsID, CorpsName, Specialization) values (133, 'Signal Battalion', 'Wildfire Control');
insert into corps (CorpsID, CorpsName, Specialization) values (134, 'Bahad 75', 'Strategic Supplies Stock');
insert into corps (CorpsID, CorpsName, Specialization) values (135, 'Shayetet 13', 'Radar Monitoring');
insert into corps (CorpsID, CorpsName, Specialization) values (136, 'Yahalom Unit', 'Leadership Mentorship');
insert into corps (CorpsID, CorpsName, Specialization) values (137, 'Cyber School', 'Ground Ops Control');
insert into corps (CorpsID, CorpsName, Specialization) values (138, 'Officer Training Command', 'Maritime Logistics');
insert into corps (CorpsID, CorpsName, Specialization) values (139, 'Combat Engineering Corps', 'E-Learning Development');
insert into corps (CorpsID, CorpsName, Specialization) values (140, 'Bahad 23', 'Infantry Tactics');
insert into corps (CorpsID, CorpsName, Specialization) values (141, 'Bahad 23', 'Weapon Testing');
insert into corps (CorpsID, CorpsName, Specialization) values (142, 'Human Resources Planning', 'Drone Piloting');
insert into corps (CorpsID, CorpsName, Specialization) values (143, 'Bahad 60', 'Backup Readiness');
insert into corps (CorpsID, CorpsName, Specialization) values (144, 'Combat Intelligence Collection Corps', 'Leadership Mentorship');
insert into corps (CorpsID, CorpsName, Specialization) values (145, 'Bahad 58', 'Tactical Navigation');
insert into corps (CorpsID, CorpsName, Specialization) values (146, 'Future Combat Systems Unit', 'Coastal Surveillance');
insert into corps (CorpsID, CorpsName, Specialization) values (147, 'Air Control Unit', 'Training Development');
insert into corps (CorpsID, CorpsName, Specialization) values (148, 'Reserve Division', 'Naval Recon');
insert into corps (CorpsID, CorpsName, Specialization) values (149, '7th Armored Brigade', 'Contraband Prevention');
insert into corps (CorpsID, CorpsName, Specialization) values (150, '188th Brigade', 'Intelligence Briefing');
insert into corps (CorpsID, CorpsName, Specialization) values (151, 'Munitions Unit', 'Weapons Development');
insert into corps (CorpsID, CorpsName, Specialization) values (152, 'Canine Unit', 'Weapon Testing');
insert into corps (CorpsID, CorpsName, Specialization) values (153, 'Border Defense Corps', 'Psychological Warfare');
insert into corps (CorpsID, CorpsName, Specialization) values (154, 'Officer School', 'Weapon Systems');
insert into corps (CorpsID, CorpsName, Specialization) values (155, 'Military Rabbinate', 'Secure Transmission');
insert into corps (CorpsID, CorpsName, Specialization) values (156, 'Field Observers Unit', 'Surveillance Posts');
insert into corps (CorpsID, CorpsName, Specialization) values (157, 'Commando Brigade', 'Urban Intelligence');
insert into corps (CorpsID, CorpsName, Specialization) values (158, 'Bahad 50', 'Resource Logistics');
insert into corps (CorpsID, CorpsName, Specialization) values (159, 'Missile Command Unit', 'Sapper Training');
insert into corps (CorpsID, CorpsName, Specialization) values (160, 'IDF Choir', 'Tactical Training');
insert into corps (CorpsID, CorpsName, Specialization) values (161, 'Air Force', 'Tactical Navigation');
insert into corps (CorpsID, CorpsName, Specialization) values (162, 'Bahad 22', 'Supply Planning');
insert into corps (CorpsID, CorpsName, Specialization) values (163, 'Weather Unit', 'Aircraft Maintenance');
insert into corps (CorpsID, CorpsName, Specialization) values (164, 'Recruitment Administration', 'Fuel Logistics');
insert into corps (CorpsID, CorpsName, Specialization) values (165, 'Flight School', 'Emergency Triage');
insert into corps (CorpsID, CorpsName, Specialization) values (166, 'Bahad 32', 'Air Service Repair');
insert into corps (CorpsID, CorpsName, Specialization) values (167, 'Bahad 13', 'Strategic Planning');
insert into corps (CorpsID, CorpsName, Specialization) values (168, 'Bahad 62', 'Intelligence Analysis');
insert into corps (CorpsID, CorpsName, Specialization) values (169, 'Reserve Administration', 'Reserve Kit Distribution');
insert into corps (CorpsID, CorpsName, Specialization) values (170, 'Bahad 42', 'Cyber Defense');
insert into corps (CorpsID, CorpsName, Specialization) values (171, 'Military Court Unit', 'Satellite Imaging');
insert into corps (CorpsID, CorpsName, Specialization) values (172, 'Field Hospitals Unit', 'Long-Term Planning');
insert into corps (CorpsID, CorpsName, Specialization) values (173, 'Bahad 33', 'High-Alert Command');
insert into corps (CorpsID, CorpsName, Specialization) values (174, 'Combat Engineering School', 'Tactical Transport');
insert into corps (CorpsID, CorpsName, Specialization) values (175, 'Special Forces HQ', 'Tactical Software');
insert into corps (CorpsID, CorpsName, Specialization) values (176, 'Naval Commando Unit', 'Rescue and Recovery');
insert into corps (CorpsID, CorpsName, Specialization) values (177, 'Bahad 46', 'Strategic Navigation');
insert into corps (CorpsID, CorpsName, Specialization) values (178, 'Bahad 75', 'Counter-Drone Tech');
insert into corps (CorpsID, CorpsName, Specialization) values (179, 'Bahad 89', 'Contraband Prevention');
insert into corps (CorpsID, CorpsName, Specialization) values (180, 'Space Administration', 'Mobile Surgery Coordination');
insert into corps (CorpsID, CorpsName, Specialization) values (181, 'Bahad 8', 'Cyber Threat Response');
insert into corps (CorpsID, CorpsName, Specialization) values (182, 'UAV Control School', 'Counter-Drone Tech');
insert into corps (CorpsID, CorpsName, Specialization) values (183, 'Search and Rescue Unit', 'Ground Ops Control');
insert into corps (CorpsID, CorpsName, Specialization) values (184, 'Combat Intelligence Collection Corps', 'Sapper Training');
insert into corps (CorpsID, CorpsName, Specialization) values (185, 'Bahad 62', 'Backup Readiness');
insert into corps (CorpsID, CorpsName, Specialization) values (186, 'Bahad 62', 'Military Court Procedure');
insert into corps (CorpsID, CorpsName, Specialization) values (187, 'Mobile Surgery Unit', 'Rapid Deployment Surgery');
insert into corps (CorpsID, CorpsName, Specialization) values (188, '7th Armored Brigade', 'Firefighting Rescue');
insert into corps (CorpsID, CorpsName, Specialization) values (189, 'Unit 8200', 'Mobile Medicine');
insert into corps (CorpsID, CorpsName, Specialization) values (190, 'Bahad 35', 'Aircraft Maintenance');
insert into corps (CorpsID, CorpsName, Specialization) values (191, 'Tactical Data Systems Unit', 'Missile Interception');
insert into corps (CorpsID, CorpsName, Specialization) values (192, 'IDF Choir', 'Performance Music');
insert into corps (CorpsID, CorpsName, Specialization) values (193, 'Munitions Unit', 'Logistical Operations');
insert into corps (CorpsID, CorpsName, Specialization) values (194, 'Navy', 'Intelligence Briefing');
insert into corps (CorpsID, CorpsName, Specialization) values (195, 'Naval Logistics Unit', 'Soldier Welfare');
insert into corps (CorpsID, CorpsName, Specialization) values (196, 'IDF NCO School', 'Data Security Policy');
insert into corps (CorpsID, CorpsName, Specialization) values (197, 'Field Hospitals Unit', 'Network Defense');
insert into corps (CorpsID, CorpsName, Specialization) values (198, 'Search and Rescue Unit', 'Geo-Political Analysis');
insert into corps (CorpsID, CorpsName, Specialization) values (199, 'Bahad 32', 'High-Alert Command');
insert into corps (CorpsID, CorpsName, Specialization) values (200, 'Bahad 40', 'Communications Design');
insert into corps (CorpsID, CorpsName, Specialization) values (201, 'Bahad 21', 'Aerial Surveillance');
insert into corps (CorpsID, CorpsName, Specialization) values (202, 'Joint Operations Unit', 'Flight Instruction');
insert into corps (CorpsID, CorpsName, Specialization) values (203, 'Bahad 89', 'Remote Sensing');
insert into corps (CorpsID, CorpsName, Specialization) values (204, 'Bahad 17', 'Helicopter Piloting');
insert into corps (CorpsID, CorpsName, Specialization) values (205, 'Combat Engineering School', 'Record Archiving');
insert into corps (CorpsID, CorpsName, Specialization) values (206, 'Bahad 59', 'Case Investigations');
insert into corps (CorpsID, CorpsName, Specialization) values (207, 'Bahad 74', 'Landmine Clearing');
insert into corps (CorpsID, CorpsName, Specialization) values (208, 'IDF Combat Academy', 'Jungle Warfare');
insert into corps (CorpsID, CorpsName, Specialization) values (209, 'Bahad 12', 'Armored Warfare');
insert into corps (CorpsID, CorpsName, Specialization) values (210, 'Kfir Brigade', 'Desert Combat');
insert into corps (CorpsID, CorpsName, Specialization) values (211, 'Signal Battalion', 'Rapid Air Assault');
insert into corps (CorpsID, CorpsName, Specialization) values (212, 'Bahad 39', 'Malware Analysis');
insert into corps (CorpsID, CorpsName, Specialization) values (213, 'Bahad 94', 'Armored Unit Recovery');
insert into corps (CorpsID, CorpsName, Specialization) values (214, 'Sniper Division', 'Weapons Development');
insert into corps (CorpsID, CorpsName, Specialization) values (215, 'Technical Operations Center', 'Secure Networks');
insert into corps (CorpsID, CorpsName, Specialization) values (216, 'Bahad 26', 'Military Law Enforcement');
insert into corps (CorpsID, CorpsName, Specialization) values (217, 'Military Police Investigations Unit', 'Naval Warfare');
insert into corps (CorpsID, CorpsName, Specialization) values (218, 'Bahad 96', 'Statistical Forecasting');
insert into corps (CorpsID, CorpsName, Specialization) values (219, 'Bahad 85', 'Weapon Testing');
insert into corps (CorpsID, CorpsName, Specialization) values (220, 'Military Intelligence School', 'Legal Defense');
insert into corps (CorpsID, CorpsName, Specialization) values (221, 'Officer Training Command', 'Threat Modeling');
insert into corps (CorpsID, CorpsName, Specialization) values (222, 'Bahad 95', 'Remote Sensing');
insert into corps (CorpsID, CorpsName, Specialization) values (223, 'Sniper Division', 'Explosive Disposal');
insert into corps (CorpsID, CorpsName, Specialization) values (224, 'Bahad 5', 'Medical Evacuation');
insert into corps (CorpsID, CorpsName, Specialization) values (225, 'Bahad 3', 'Long-Term Planning');
insert into corps (CorpsID, CorpsName, Specialization) values (226, 'Offensive Cyber Unit', 'Strategic Intel Command');
insert into corps (CorpsID, CorpsName, Specialization) values (227, 'Data Security Department', 'Surveillance Analytics');
insert into corps (CorpsID, CorpsName, Specialization) values (228, 'Sayeret Matkal', 'Flight Instruction');
insert into corps (CorpsID, CorpsName, Specialization) values (229, 'Bahad 98', 'Network Defense');
insert into corps (CorpsID, CorpsName, Specialization) values (230, 'Rocket Launcher Unit', 'Malware Analysis');
insert into corps (CorpsID, CorpsName, Specialization) values (231, 'Military Intelligence School', 'Battlefield Diagnosis');
insert into corps (CorpsID, CorpsName, Specialization) values (232, 'Transport Squadron', 'Surveillance Posts');
insert into corps (CorpsID, CorpsName, Specialization) values (233, 'Egoz Unit', 'Tactical Software');
insert into corps (CorpsID, CorpsName, Specialization) values (234, 'Duvdevan Unit', 'Wildfire Control');
insert into corps (CorpsID, CorpsName, Specialization) values (235, 'C4I Corps', 'Backup Readiness');
insert into corps (CorpsID, CorpsName, Specialization) values (236, 'Bahad 47', 'Weapons Development');
insert into corps (CorpsID, CorpsName, Specialization) values (237, 'Bahad 49', 'Underwater Missions');
insert into corps (CorpsID, CorpsName, Specialization) values (238, 'Strategy Division', 'Morale Assessment');
insert into corps (CorpsID, CorpsName, Specialization) values (239, 'Sniper Division', 'Satellite Comm Tracking');
insert into corps (CorpsID, CorpsName, Specialization) values (240, 'Bahad 47', 'Surveillance Drone Ops');
insert into corps (CorpsID, CorpsName, Specialization) values (241, 'Military Rabbinate', 'Special Operations');
insert into corps (CorpsID, CorpsName, Specialization) values (242, 'Balloon Surveillance Unit', 'Intelligence Briefing');
insert into corps (CorpsID, CorpsName, Specialization) values (243, 'Bahad 25', 'Innovation Prototyping');
insert into corps (CorpsID, CorpsName, Specialization) values (244, 'Bahad 24', 'Desert Patrol');
insert into corps (CorpsID, CorpsName, Specialization) values (245, 'Training Division', 'Future Systems Design');
insert into corps (CorpsID, CorpsName, Specialization) values (246, 'Airborne Assault Unit', 'Radar Installation');
insert into corps (CorpsID, CorpsName, Specialization) values (247, 'Bahad 15', 'Morale Assessment');
insert into corps (CorpsID, CorpsName, Specialization) values (248, 'Kfir Brigade', 'Jungle Warfare');
insert into corps (CorpsID, CorpsName, Specialization) values (249, 'Field Observers Unit', 'Innovation Prototyping');
insert into corps (CorpsID, CorpsName, Specialization) values (250, 'Instructional Design Unit', 'HR Metrics');
insert into corps (CorpsID, CorpsName, Specialization) values (251, 'Balloon Surveillance Unit', 'Urban Search and Rescue');
insert into corps (CorpsID, CorpsName, Specialization) values (252, 'Advanced Weapons Unit', 'Border Surveillance');
insert into corps (CorpsID, CorpsName, Specialization) values (253, 'Paratroopers Brigade', 'Operational Strategy');
insert into corps (CorpsID, CorpsName, Specialization) values (254, 'Bahad 86', 'Jungle Warfare');
insert into corps (CorpsID, CorpsName, Specialization) values (255, 'Armored Corps', 'Backup Readiness');
insert into corps (CorpsID, CorpsName, Specialization) values (256, 'Northern Rescue Unit', 'Satellite Comm Tracking');
insert into corps (CorpsID, CorpsName, Specialization) values (257, 'Sea Corps Base', 'Network Defense');
insert into corps (CorpsID, CorpsName, Specialization) values (258, 'Academic Officers Program', 'Landmine Clearing');
insert into corps (CorpsID, CorpsName, Specialization) values (259, 'Southern Command', 'Aerial Extraction');
insert into corps (CorpsID, CorpsName, Specialization) values (260, 'Artillery School', 'Base Construction');
insert into corps (CorpsID, CorpsName, Specialization) values (261, 'Operational Medicine Unit', 'Cyber Defense');
insert into corps (CorpsID, CorpsName, Specialization) values (262, 'Training Division', 'Demolition Engineering');
insert into corps (CorpsID, CorpsName, Specialization) values (263, 'Armored Corps', 'Cyber Tactics');
insert into corps (CorpsID, CorpsName, Specialization) values (264, 'Strategic Command Unit', 'High-Altitude Recon');
insert into corps (CorpsID, CorpsName, Specialization) values (265, 'Military Intelligence School', 'Tank Command');
insert into corps (CorpsID, CorpsName, Specialization) values (266, 'Air Intelligence Unit', 'Cyber Threat Response');
insert into corps (CorpsID, CorpsName, Specialization) values (267, 'Military Archive Unit', 'Heavy Vehicle Logistics');
insert into corps (CorpsID, CorpsName, Specialization) values (268, 'Bahad 93', 'Aircraft Maintenance');
insert into corps (CorpsID, CorpsName, Specialization) values (269, 'Bahad 44', 'Air Defense Operations');
insert into corps (CorpsID, CorpsName, Specialization) values (270, 'Northern Engineering Battalion', 'Communications Tower Setup');
insert into corps (CorpsID, CorpsName, Specialization) values (271, 'Military Trucking Unit', 'Signal Intelligence');
insert into corps (CorpsID, CorpsName, Specialization) values (272, 'Bahad 8', 'Rocket System Ops');
insert into corps (CorpsID, CorpsName, Specialization) values (273, 'Legal Corps', 'Aerial Data Analysis');
insert into corps (CorpsID, CorpsName, Specialization) values (274, 'Bahad 95', 'Ballistic Defense');
insert into corps (CorpsID, CorpsName, Specialization) values (275, 'Signal Battalion', 'Reserve Kit Distribution');
insert into corps (CorpsID, CorpsName, Specialization) values (276, 'UAV Unit', 'Tactical Radio Setup');
insert into corps (CorpsID, CorpsName, Specialization) values (277, 'IDF Combat Academy', 'Missile Guidance');
insert into corps (CorpsID, CorpsName, Specialization) values (278, 'Sniper Division', 'Intelligence Schooling');
insert into corps (CorpsID, CorpsName, Specialization) values (279, 'Bahad 79', 'Performance Music');
insert into corps (CorpsID, CorpsName, Specialization) values (280, 'Mobile Surgery Unit', 'Reserve Kit Distribution');
insert into corps (CorpsID, CorpsName, Specialization) values (281, 'Bahad 87', 'Air Threat Detection');
insert into corps (CorpsID, CorpsName, Specialization) values (282, 'Satellite Intelligence Unit', 'Religious Support');
insert into corps (CorpsID, CorpsName, Specialization) values (283, 'Oketz Unit', 'Field Surgery');
insert into corps (CorpsID, CorpsName, Specialization) values (284, 'Special Operations Command', 'Missile Guidance');
insert into corps (CorpsID, CorpsName, Specialization) values (285, 'Bahad 94', 'Air Service Repair');
insert into corps (CorpsID, CorpsName, Specialization) values (286, 'Human Resources Planning', 'Battlefield Diagnosis');
insert into corps (CorpsID, CorpsName, Specialization) values (287, 'Military Police Investigations Unit', 'Warhead Logistics');
insert into corps (CorpsID, CorpsName, Specialization) values (288, 'Maglan Unit', 'Air Service Repair');
insert into corps (CorpsID, CorpsName, Specialization) values (289, 'Bahad 50', 'Resource Logistics');
insert into corps (CorpsID, CorpsName, Specialization) values (290, 'Bahad 40', 'Naval Warfare');
insert into corps (CorpsID, CorpsName, Specialization) values (291, 'Infantry Corps', 'Armored Warfare');
insert into corps (CorpsID, CorpsName, Specialization) values (292, 'Combat Engineering School', 'Warhead Logistics');
insert into corps (CorpsID, CorpsName, Specialization) values (293, 'IDF Orchestra', 'Surveillance Analytics');
insert into corps (CorpsID, CorpsName, Specialization) values (294, 'Mobile Surgery Unit', 'Urban Search and Rescue');
insert into corps (CorpsID, CorpsName, Specialization) values (295, 'David’s Sling Unit', 'Weapon Systems');
insert into corps (CorpsID, CorpsName, Specialization) values (296, 'Navy Diving School', 'Record Archiving');
insert into corps (CorpsID, CorpsName, Specialization) values (297, 'Logistics Corps', 'Music Instruction');
insert into corps (CorpsID, CorpsName, Specialization) values (298, 'Northern Rescue Unit', 'Aerial Defense');
insert into corps (CorpsID, CorpsName, Specialization) values (299, 'Bahad 53', 'Air Threat Detection');
insert into corps (CorpsID, CorpsName, Specialization) values (300, 'Bahad 93', 'Maritime Rescue');
insert into corps (CorpsID, CorpsName, Specialization) values (301, 'Bahad 79', 'Ammo Storage');
insert into corps (CorpsID, CorpsName, Specialization) values (302, 'Armored Recovery Unit', 'Heavy Vehicle Logistics');
insert into corps (CorpsID, CorpsName, Specialization) values (303, 'Weather Unit', 'Combat Fitness');
insert into corps (CorpsID, CorpsName, Specialization) values (304, 'Bahad 1', 'Battlefield Diagnosis');
insert into corps (CorpsID, CorpsName, Specialization) values (305, 'Bahad 40', 'Air Photo Interpretation');
insert into corps (CorpsID, CorpsName, Specialization) values (306, 'Intelligence Directorate', 'Desert Patrol');
insert into corps (CorpsID, CorpsName, Specialization) values (307, 'Southern Engineering Battalion', 'Paratrooper Recon');
insert into corps (CorpsID, CorpsName, Specialization) values (308, 'Mobile Surgery Unit', 'Leadership Mentorship');
insert into corps (CorpsID, CorpsName, Specialization) values (309, 'Bahad 90', 'Radio Communication');
insert into corps (CorpsID, CorpsName, Specialization) values (310, 'Bahad 16', 'Mechanical Maintenance');
insert into corps (CorpsID, CorpsName, Specialization) values (311, 'Border Observation Company', 'Helicopter Piloting');
insert into corps (CorpsID, CorpsName, Specialization) values (312, 'Cyber Warfare Command', 'Training Development');
insert into corps (CorpsID, CorpsName, Specialization) values (313, 'Bahad 89', 'CBRN Safety');
insert into corps (CorpsID, CorpsName, Specialization) values (314, 'Bahad 12', 'Morale Assessment');
insert into corps (CorpsID, CorpsName, Specialization) values (315, 'Bahad 95', 'Tactical Supply Drops');
insert into corps (CorpsID, CorpsName, Specialization) values (316, 'Sniper Division', 'Draft Planning');
insert into corps (CorpsID, CorpsName, Specialization) values (317, 'Unit 81', 'Counterterrorism');
insert into corps (CorpsID, CorpsName, Specialization) values (318, 'Bahad 70', 'Geo-Intelligence');
insert into corps (CorpsID, CorpsName, Specialization) values (319, 'Bahad 42', 'Commando Infiltration');
insert into corps (CorpsID, CorpsName, Specialization) values (320, 'Bahad 51', 'Heavy Vehicle Logistics');
insert into corps (CorpsID, CorpsName, Specialization) values (321, 'Duvdevan Unit', 'Submarine Navigation');
insert into corps (CorpsID, CorpsName, Specialization) values (322, 'Combat Engineering Corps', 'Detention Facility Security');
insert into corps (CorpsID, CorpsName, Specialization) values (323, 'Bahad 44', 'Secure Transmission');
insert into corps (CorpsID, CorpsName, Specialization) values (324, 'UAV Unit', 'Land Warfare Strategy');
insert into corps (CorpsID, CorpsName, Specialization) values (325, 'Satellite Intelligence Unit', 'Sapper Training');
insert into corps (CorpsID, CorpsName, Specialization) values (326, 'Logistics Corps', 'Signal Intelligence');
insert into corps (CorpsID, CorpsName, Specialization) values (327, 'Radar Unit', 'Weapons Development');
insert into corps (CorpsID, CorpsName, Specialization) values (328, 'Naval Commando Unit', 'Detention Facility Security');
insert into corps (CorpsID, CorpsName, Specialization) values (329, 'IDF Choir', 'Battlefield Diagnosis');
insert into corps (CorpsID, CorpsName, Specialization) values (330, 'Military Trucking Unit', 'Reserve Kit Distribution');
insert into corps (CorpsID, CorpsName, Specialization) values (331, 'Technical Operations Center', 'Recruitment Strategy');
insert into corps (CorpsID, CorpsName, Specialization) values (332, 'Airborne Assault Unit', 'Rapid Air Assault');
insert into corps (CorpsID, CorpsName, Specialization) values (333, 'Coastal Defense Unit', 'Operational Strategy');
insert into corps (CorpsID, CorpsName, Specialization) values (334, 'EOD Unit', 'Signal Intelligence');
insert into corps (CorpsID, CorpsName, Specialization) values (335, 'CBRN Unit', 'Border Patrol');
insert into corps (CorpsID, CorpsName, Specialization) values (336, 'Bahad 20', 'Equipment Allocation');
insert into corps (CorpsID, CorpsName, Specialization) values (337, 'Bahad 3', 'Rapid Air Assault');
insert into corps (CorpsID, CorpsName, Specialization) values (338, 'Special Forces HQ', 'Infantry Tactics');
insert into corps (CorpsID, CorpsName, Specialization) values (339, 'Border Defense Corps', 'Strategic Intel Command');
insert into corps (CorpsID, CorpsName, Specialization) values (340, 'Field Observers Unit', 'Armored Warfare');
insert into corps (CorpsID, CorpsName, Specialization) values (341, 'Dog Training School', 'Special Operations');
insert into corps (CorpsID, CorpsName, Specialization) values (342, 'Military Police Corps', 'Weapon Testing');
insert into corps (CorpsID, CorpsName, Specialization) values (343, 'UAV Control School', 'Innovation Prototyping');
insert into corps (CorpsID, CorpsName, Specialization) values (344, 'Bahad 41', 'Budget Management');
insert into corps (CorpsID, CorpsName, Specialization) values (345, 'Bahad 66', 'Geo-Political Analysis');
insert into corps (CorpsID, CorpsName, Specialization) values (346, 'Bahad 75', 'Target Acquisition');
insert into corps (CorpsID, CorpsName, Specialization) values (347, 'Bahad 11', 'Paratrooper Recon');
insert into corps (CorpsID, CorpsName, Specialization) values (348, 'Arrow Missile Unit', 'Leadership Mentorship');
insert into corps (CorpsID, CorpsName, Specialization) values (349, 'Naval Instruction School', 'Enemy Movement Analysis');
insert into corps (CorpsID, CorpsName, Specialization) values (350, 'Bahad 49', 'Surveillance Posts');
insert into corps (CorpsID, CorpsName, Specialization) values (351, 'Bahad 62', 'Combat Fitness');
insert into corps (CorpsID, CorpsName, Specialization) values (352, 'Southern Command', 'Naval Assault');
insert into corps (CorpsID, CorpsName, Specialization) values (353, 'Bahad 74', 'Launcher Setup');
insert into corps (CorpsID, CorpsName, Specialization) values (354, '188th Brigade', 'Draft Planning');
insert into corps (CorpsID, CorpsName, Specialization) values (355, 'Military Planning Division', 'Commander Training');
insert into corps (CorpsID, CorpsName, Specialization) values (356, 'Paratrooper Recon Unit', 'Launcher Setup');
insert into corps (CorpsID, CorpsName, Specialization) values (357, 'Commando Brigade', 'Performance Music');
insert into corps (CorpsID, CorpsName, Specialization) values (358, 'Munitions Unit', 'Budget Management');
insert into corps (CorpsID, CorpsName, Specialization) values (359, 'Bahad 31', 'E-Learning Development');
insert into corps (CorpsID, CorpsName, Specialization) values (360, 'Naval Commando Unit', 'Emergency Depot');
insert into corps (CorpsID, CorpsName, Specialization) values (361, 'Bahad 68', 'Educational Program Development');
insert into corps (CorpsID, CorpsName, Specialization) values (362, 'Officer School', 'Land Warfare Strategy');
insert into corps (CorpsID, CorpsName, Specialization) values (363, 'Medical School', 'Military Networking');
insert into corps (CorpsID, CorpsName, Specialization) values (364, 'Recruitment Administration', 'High-Alert Command');
insert into corps (CorpsID, CorpsName, Specialization) values (365, 'Military Rabbinate', 'Combat Network Ops');
insert into corps (CorpsID, CorpsName, Specialization) values (366, 'Munitions Unit', 'Intelligence Schooling');
insert into corps (CorpsID, CorpsName, Specialization) values (367, 'Radar Unit', 'Guerrilla Warfare');
insert into corps (CorpsID, CorpsName, Specialization) values (368, 'Unit 8200', 'Air Defense Operations');
insert into corps (CorpsID, CorpsName, Specialization) values (369, 'Intelligence Research Department', 'Flight Instruction');
insert into corps (CorpsID, CorpsName, Specialization) values (370, 'Bahad 33', 'Maritime Logistics');
insert into corps (CorpsID, CorpsName, Specialization) values (371, 'Education and Youth Corps', 'Budget Management');
insert into corps (CorpsID, CorpsName, Specialization) values (372, 'Air Intelligence Unit', 'Drone Piloting');
insert into corps (CorpsID, CorpsName, Specialization) values (373, 'Bahad 12', 'Surveillance Drone Ops');
insert into corps (CorpsID, CorpsName, Specialization) values (374, 'Bahad 15', 'Draft Planning');
insert into corps (CorpsID, CorpsName, Specialization) values (375, 'Anti-Aircraft Unit', 'Combat Preparation');
insert into corps (CorpsID, CorpsName, Specialization) values (376, 'Field Observers Unit', 'UAV Assembly');
insert into corps (CorpsID, CorpsName, Specialization) values (377, 'Logistics School', 'Land Warfare Strategy');
insert into corps (CorpsID, CorpsName, Specialization) values (378, 'Logistics Corps', 'Case Investigations');
insert into corps (CorpsID, CorpsName, Specialization) values (379, 'Intelligence Directorate', 'Code Analysis');
insert into corps (CorpsID, CorpsName, Specialization) values (380, 'Bahad 12', 'Satellite Comm Tracking');
insert into corps (CorpsID, CorpsName, Specialization) values (381, 'Cyber Warfare Command', 'Launcher Setup');
insert into corps (CorpsID, CorpsName, Specialization) values (382, 'Lotar Counter-Terror School', 'Cyber Espionage');
insert into corps (CorpsID, CorpsName, Specialization) values (383, 'Military Law School', 'Network Defense');
insert into corps (CorpsID, CorpsName, Specialization) values (384, 'Air Force', 'Rescue and Recovery');
insert into corps (CorpsID, CorpsName, Specialization) values (385, 'Submarine Flotilla', 'Naval Assault');
insert into corps (CorpsID, CorpsName, Specialization) values (386, 'Reserve Administration', 'Draft Planning');
insert into corps (CorpsID, CorpsName, Specialization) values (387, 'CBRN Unit', 'Remote Sensing');
insert into corps (CorpsID, CorpsName, Specialization) values (388, 'Military Police Investigations Unit', 'Communications Design');
insert into corps (CorpsID, CorpsName, Specialization) values (389, 'Bahad 80', 'Armored Vehicle Recovery');
insert into corps (CorpsID, CorpsName, Specialization) values (390, 'Bahad 63', 'Supply Chain Logistics');
insert into corps (CorpsID, CorpsName, Specialization) values (391, 'Bahad 54', 'Infantry Operations');
insert into corps (CorpsID, CorpsName, Specialization) values (392, 'Bahad 68', 'Tactical Training');
insert into corps (CorpsID, CorpsName, Specialization) values (393, 'Rocket Launcher Unit', 'Air Defense Operations');
insert into corps (CorpsID, CorpsName, Specialization) values (394, 'Home Front Rescue Brigade', 'Supply Planning');
insert into corps (CorpsID, CorpsName, Specialization) values (395, 'Armored Corps', 'Weapon Systems');
insert into corps (CorpsID, CorpsName, Specialization) values (396, 'Bahad 94', 'Remote Sensing');
insert into corps (CorpsID, CorpsName, Specialization) values (397, 'Bahad 47', 'Armored Warfare');
insert into corps (CorpsID, CorpsName, Specialization) values (398, 'UAV Control School', 'Virtual Sim Training');
insert into corps (CorpsID, CorpsName, Specialization) values (399, 'Bahad 91', 'Border Interception');
insert into corps (CorpsID, CorpsName, Specialization) values (400, 'Data Security Department', 'Surveillance Posts');
