insert into Corps (CorpsID, CorpsName) values (1, 'Infantry Corps');
insert into Corps (CorpsID, CorpsName) values (2, 'Armored Corps');
insert into Corps (CorpsID, CorpsName) values (3, 'Artillery Corps');
insert into Corps (CorpsID, CorpsName) values (4, 'Combat Intelligence Corps');
insert into Corps (CorpsID, CorpsName) values (5, 'Signal Corps');
insert into Corps (CorpsID, CorpsName) values (6, 'Engineering Corps');
insert into Corps (CorpsID, CorpsName) values (7, 'Medical Corps');
insert into Corps (CorpsID, CorpsName) values (8, 'Logistics Corps');
insert into Corps (CorpsID, CorpsName) values (9, 'Military Police Corps');
insert into Corps (CorpsID, CorpsName) values (10, 'Air Force');
insert into Corps (CorpsID, CorpsName) values (11, 'Navy');
insert into Corps (CorpsID, CorpsName) values (12, 'Cyber Warfare Corps');
insert into Corps (CorpsID, CorpsName) values (13, 'Reconnaissance Corps');
insert into Corps (CorpsID, CorpsName) values (14, 'Special Forces');
insert into Corps (CorpsID, CorpsName) values (15, 'Search and Rescue Corps');
insert into Corps (CorpsID, CorpsName) values (16, 'Intelligence Corps');
insert into Corps (CorpsID, CorpsName) values (17, 'Psychological Warfare Corps');
insert into Corps (CorpsID, CorpsName) values (18, 'Chemical Warfare Corps');
insert into Corps (CorpsID, CorpsName) values (19, 'Military Government Corps');
insert into Corps (CorpsID, CorpsName) values (20, 'Border Patrol Corps');
insert into Corps (CorpsID, CorpsName) values (21, 'Military Training Corps');
insert into Corps (CorpsID, CorpsName) values (22, 'Tactical Operations Corps');
insert into Corps (CorpsID, CorpsName) values (23, 'Communications Corps');
insert into Corps (CorpsID, CorpsName) values (24, 'Military Aviation Corps');
insert into Corps (CorpsID, CorpsName) values (25, 'Reserve Forces Corps');
insert into Corps (CorpsID, CorpsName) values (26, 'Equipment Maintenance Corps');
insert into Corps (CorpsID, CorpsName) values (27, 'Transport Corps');
insert into Corps (CorpsID, CorpsName) values (28, 'Military Intelligence Corps');
insert into Corps (CorpsID, CorpsName) values (29, 'Military Electronics Corps');
insert into Corps (CorpsID, CorpsName) values (30, 'Military Ordnance Corps');
insert into Corps (CorpsID, CorpsName) values (31, 'Military Engineering Corps');
insert into Corps (CorpsID, CorpsName) values (32, 'Heavy Equipment Corps');
insert into Corps (CorpsID, CorpsName) values (33, 'Infantry Special Operations Corps');
insert into Corps (CorpsID, CorpsName) values (34, 'Paratroopers Corps');
insert into Corps (CorpsID, CorpsName) values (35, 'Coastal Defense Corps');
insert into Corps (CorpsID, CorpsName) values (36, 'Missile Defense Corps');
insert into Corps (CorpsID, CorpsName) values (37, 'Army Radio Corps');
insert into Corps (CorpsID, CorpsName) values (38, 'Logistics and Supply Corps');
insert into Corps (CorpsID, CorpsName) values (39, 'Air Defense Corps');
insert into Corps (CorpsID, CorpsName) values (40, 'Technology and Innovation Corps');
insert into Corps (CorpsID, CorpsName) values (41, 'Defense Strategy Corps');
insert into Corps (CorpsID, CorpsName) values (42, 'Cyber Security Corps');
insert into Corps (CorpsID, CorpsName) values (43, 'Intelligence and Surveillance Corps');
insert into Corps (CorpsID, CorpsName) values (44, 'Rescue and Recovery Corps');
insert into Corps (CorpsID, CorpsName) values (45, 'Desert Warfare Corps');
insert into Corps (CorpsID, CorpsName) values (46, 'Maritime Warfare Corps');
insert into Corps (CorpsID, CorpsName) values (47, 'Combat Medical Corps');
insert into Corps (CorpsID, CorpsName) values (48, 'Psychological Operations Corps');
insert into Corps (CorpsID, CorpsName) values (49, 'Watercraft Corps');
insert into Corps (CorpsID, CorpsName) values (50, 'Command and Control Corps');
insert into Corps (CorpsID, CorpsName) values (51, 'Heavy Logistics Corps');
insert into Corps (CorpsID, CorpsName) values (52, 'Tactical Support Corps');
insert into Corps (CorpsID, CorpsName) values (53, 'Army Medical Research Corps');
insert into Corps (CorpsID, CorpsName) values (54, 'Urban Warfare Corps');
insert into Corps (CorpsID, CorpsName) values (55, 'Remote Sensing Corps');
insert into Corps (CorpsID, CorpsName) values (56, 'Special Reconnaissance Corps');
insert into Corps (CorpsID, CorpsName) values (57, 'Communications Intelligence Corps');
insert into Corps (CorpsID, CorpsName) values (58, 'Fire Support Corps');
insert into Corps (CorpsID, CorpsName) values (59, 'Military Sports Corps');
insert into Corps (CorpsID, CorpsName) values (60, 'Army Combat Training Corps');
insert into Corps (CorpsID, CorpsName) values (61, 'Medical Evacuation Corps');
insert into Corps (CorpsID, CorpsName) values (62, 'Field Engineers Corps');
insert into Corps (CorpsID, CorpsName) values (63, 'Field Artillery Corps');
insert into Corps (CorpsID, CorpsName) values (64, 'Military Communications Corps');
insert into Corps (CorpsID, CorpsName) values (65, 'Combat Support Corps');
insert into Corps (CorpsID, CorpsName) values (66, 'Firefighting Corps');
insert into Corps (CorpsID, CorpsName) values (67, 'Border Security Corps');
insert into Corps (CorpsID, CorpsName) values (68, 'Military Operations Corps');
insert into Corps (CorpsID, CorpsName) values (69, 'Electronic Warfare Corps');
insert into Corps (CorpsID, CorpsName) values (70, 'Naval Intelligence Corps');
insert into Corps (CorpsID, CorpsName) values (71, 'Special Air Service Corps');
insert into Corps (CorpsID, CorpsName) values (72, 'Armed Forces Band Corps');
insert into Corps (CorpsID, CorpsName) values (73, 'Light Infantry Corps');
insert into Corps (CorpsID, CorpsName) values (74, 'Heavy Infantry Corps');
insert into Corps (CorpsID, CorpsName) values (75, 'Military Science Corps');
insert into Corps (CorpsID, CorpsName) values (76, 'Logistics Support Corps');
insert into Corps (CorpsID, CorpsName) values (77, 'Coastal Patrol Corps');
insert into Corps (CorpsID, CorpsName) values (78, 'Advanced Warfare Corps');
insert into Corps (CorpsID, CorpsName) values (79, 'Tactical Rescue Corps');
insert into Corps (CorpsID, CorpsName) values (80, 'Engineering Support Corps');
insert into Corps (CorpsID, CorpsName) values (81, 'Army Aviation Corps');
insert into Corps (CorpsID, CorpsName) values (82, 'Heavy Transport Corps');
insert into Corps (CorpsID, CorpsName) values (83, 'Military Mapping Corps');
insert into Corps (CorpsID, CorpsName) values (84, 'Combat Logistics Corps');
insert into Corps (CorpsID, CorpsName) values (85, 'Army Maintenance Corps');
insert into Corps (CorpsID, CorpsName) values (86, 'Counterintelligence Corps');
insert into Corps (CorpsID, CorpsName) values (87, 'Military Construction Corps');
insert into Corps (CorpsID, CorpsName) values (88, 'Urban Security Corps');
insert into Corps (CorpsID, CorpsName) values (89, 'Crisis Response Corps');
insert into Corps (CorpsID, CorpsName) values (90, 'Special Weapons Corps');
insert into Corps (CorpsID, CorpsName) values (91, 'Combat Engineers Corps');
insert into Corps (CorpsID, CorpsName) values (92, 'Military Law Enforcement Corps');
insert into Corps (CorpsID, CorpsName) values (93, 'Strategic Command Corps');
insert into Corps (CorpsID, CorpsName) values (94, 'Joint Operations Corps');
insert into Corps (CorpsID, CorpsName) values (95, 'Cyber Defense Corps');
insert into Corps (CorpsID, CorpsName) values (96, 'Communication Networks Corps');
insert into Corps (CorpsID, CorpsName) values (97, 'Special Operations Forces');
insert into Corps (CorpsID, CorpsName) values (98, 'Airborne Corps');
insert into Corps (CorpsID, CorpsName) values (99, 'Military Aviation Maintenance Corps');
insert into Corps (CorpsID, CorpsName) values (100, 'Humanitarian Assistance Corps');
insert into Corps (CorpsID, CorpsName) values (101, 'Vehicle Repair Corps');
insert into Corps (CorpsID, CorpsName) values (102, 'Battlefield Surveillance Corps');
insert into Corps (CorpsID, CorpsName) values (103, 'Tactical Communications Corps');
insert into Corps (CorpsID, CorpsName) values (104, 'Specialized Infantry Corps');
insert into Corps (CorpsID, CorpsName) values (105, 'Logistics Planning Corps');
insert into Corps (CorpsID, CorpsName) values (106, 'Combat Aviation Corps');
insert into Corps (CorpsID, CorpsName) values (107, 'Military Simulation Corps');
insert into Corps (CorpsID, CorpsName) values (108, 'Rapid Deployment Corps');
insert into Corps (CorpsID, CorpsName) values (109, 'Military Research Corps');
insert into Corps (CorpsID, CorpsName) values (110, 'Border Defense Corps');
insert into Corps (CorpsID, CorpsName) values (111, 'Cyber Intelligence Corps');
insert into Corps (CorpsID, CorpsName) values (112, 'Advanced Electronics Corps');
insert into Corps (CorpsID, CorpsName) values (113, 'Security and Protection Corps');
insert into Corps (CorpsID, CorpsName) values (114, 'Air Transport Corps');
insert into Corps (CorpsID, CorpsName) values (115, 'Joint Combat Corps');
insert into Corps (CorpsID, CorpsName) values (116, 'Psychological Health Corps');
insert into Corps (CorpsID, CorpsName) values (117, 'Integrated Defense Corps');
insert into Corps (CorpsID, CorpsName) values (118, 'Tactical Communications Corps');
insert into Corps (CorpsID, CorpsName) values (119, 'Combat Engineering Support Corps');
insert into Corps (CorpsID, CorpsName) values (120, 'Army Medical Logistics Corps');
insert into Corps (CorpsID, CorpsName) values (121, 'Peacekeeping Operations Corps');
insert into Corps (CorpsID, CorpsName) values (122, 'Strategic Reconnaissance Corps');
insert into Corps (CorpsID, CorpsName) values (123, 'Tactical Supply Corps');
insert into Corps (CorpsID, CorpsName) values (124, 'Electronic Countermeasures Corps');
insert into Corps (CorpsID, CorpsName) values (125, 'Urban Combat Training Corps');
insert into Corps (CorpsID, CorpsName) values (126, 'Tank Battalion Corps');
insert into Corps (CorpsID, CorpsName) values (127, 'Military Psychological Health Corps');
insert into Corps (CorpsID, CorpsName) values (128, 'Humanitarian Logistics Corps');
insert into Corps (CorpsID, CorpsName) values (129, 'Technology Research Corps');
insert into Corps (CorpsID, CorpsName) values (130, 'Battlefield Communications Corps');
insert into Corps (CorpsID, CorpsName) values (131, 'Command Support Corps');
insert into Corps (CorpsID, CorpsName) values (132, 'Coastal Defense and Security Corps');
insert into Corps (CorpsID, CorpsName) values (133, 'Army Command Corps');
insert into Corps (CorpsID, CorpsName) values (134, 'Counterterrorism Corps');
insert into Corps (CorpsID, CorpsName) values (135, 'Heavy Weapons Corps');
insert into Corps (CorpsID, CorpsName) values (136, 'Strategic Airlift Corps');
insert into Corps (CorpsID, CorpsName) values (137, 'Electronic Surveillance Corps');
insert into Corps (CorpsID, CorpsName) values (138, 'Chemical and Biological Defense Corps');
insert into Corps (CorpsID, CorpsName) values (139, 'Advanced Weaponry Corps');
insert into Corps (CorpsID, CorpsName) values (140, 'Military Security Corps');
insert into Corps (CorpsID, CorpsName) values (141, 'Ammunition Support Corps');
insert into Corps (CorpsID, CorpsName) values (142, 'Logistics Engineering Corps');
insert into Corps (CorpsID, CorpsName) values (143, 'Remote Operations Corps');
insert into Corps (CorpsID, CorpsName) values (144, 'Medical Research Corps');
insert into Corps (CorpsID, CorpsName) values (145, 'Counter-Terror Operations Corps');
insert into Corps (CorpsID, CorpsName) values (146, 'Combat Health Corps');
insert into Corps (CorpsID, CorpsName) values (147, 'Military Hazardous Materials Corps');
insert into Corps (CorpsID, CorpsName) values (148, 'Search and Rescue Support Corps');
insert into Corps (CorpsID, CorpsName) values (149, 'CBRN Defense Corps');
insert into Corps (CorpsID, CorpsName) values (150, 'Tactical Air Support Corps');
insert into Corps (CorpsID, CorpsName) values (151, 'Cyber Research Corps');
insert into Corps (CorpsID, CorpsName) values (152, 'Amphibious Warfare Corps');
insert into Corps (CorpsID, CorpsName) values (153, 'Cyber Warfare Support Corps');
insert into Corps (CorpsID, CorpsName) values (154, 'Civilian Protection Corps');
insert into Corps (CorpsID, CorpsName) values (155, 'Psychological Warfare Support Corps');
insert into Corps (CorpsID, CorpsName) values (156, 'Rapid Response Corps');
insert into Corps (CorpsID, CorpsName) values (157, 'Special Recon Corps');
insert into Corps (CorpsID, CorpsName) values (158, 'Logistics and Rescue Corps');
insert into Corps (CorpsID, CorpsName) values (159, 'Army Medical Support Corps');
insert into Corps (CorpsID, CorpsName) values (160, 'Infrastructure Protection Corps');
insert into Corps (CorpsID, CorpsName) values (161, 'Emergency Response Corps');
insert into Corps (CorpsID, CorpsName) values (162, 'Battlefield Technology Corps');
insert into Corps (CorpsID, CorpsName) values (163, 'Armored Reconnaissance Corps');
insert into Corps (CorpsID, CorpsName) values (164, 'Military Hospital Corps');
insert into Corps (CorpsID, CorpsName) values (165, 'Electronic Defense Corps');
insert into Corps (CorpsID, CorpsName) values (166, 'Recon and Surveillance Corps');
insert into Corps (CorpsID, CorpsName) values (167, 'Urban Security Support Corps');
insert into Corps (CorpsID, CorpsName) values (168, 'Special Combat Corps');
insert into Corps (CorpsID, CorpsName) values (169, 'Ground Defense Corps');
insert into Corps (CorpsID, CorpsName) values (170, 'Military Scientific Research Corps');
insert into Corps (CorpsID, CorpsName) values (171, 'Military Satellite Communications Corps');
insert into Corps (CorpsID, CorpsName) values (172, 'Combat Medicine Corps');
insert into Corps (CorpsID, CorpsName) values (173, 'Advanced Field Corps');
insert into Corps (CorpsID, CorpsName) values (174, 'Tactical Rescue Support Corps');
insert into Corps (CorpsID, CorpsName) values (175, 'Military Human Resources Corps');
insert into Corps (CorpsID, CorpsName) values (176, 'Counterintelligence Support Corps');
insert into Corps (CorpsID, CorpsName) values (177, 'Airborne Rescue Corps');
insert into Corps (CorpsID, CorpsName) values (178, 'Heavy Construction Corps');
insert into Corps (CorpsID, CorpsName) values (179, 'Combat Intelligence Support Corps');
insert into Corps (CorpsID, CorpsName) values (180, 'Special Air Operations Corps');
insert into Corps (CorpsID, CorpsName) values (181, 'Strategic Defense Corps');
insert into Corps (CorpsID, CorpsName) values (182, 'Combat Command Corps');
insert into Corps (CorpsID, CorpsName) values (183, 'Advanced Logistics Support Corps');
insert into Corps (CorpsID, CorpsName) values (184, 'Strategic Air Corps');
insert into Corps (CorpsID, CorpsName) values (185, 'Military Field Operations Corps');
insert into Corps (CorpsID, CorpsName) values (186, 'Vehicle and Equipment Corps');
insert into Corps (CorpsID, CorpsName) values (187, 'Military Disaster Relief Corps');
insert into Corps (CorpsID, CorpsName) values (188, 'Search Operations Corps');
insert into Corps (CorpsID, CorpsName) values (189, 'Army Fire Support Corps');
insert into Corps (CorpsID, CorpsName) values (190, 'Emergency Medical Corps');
insert into Corps (CorpsID, CorpsName) values (191, 'Defense Systems Research Corps');
insert into Corps (CorpsID, CorpsName) values (192, 'Ground Security Corps');
insert into Corps (CorpsID, CorpsName) values (193, 'Surveillance Support Corps');
insert into Corps (CorpsID, CorpsName) values (194, 'Advanced Tactical Training Corps');
insert into Corps (CorpsID, CorpsName) values (195, 'Mobile Defense Corps');
insert into Corps (CorpsID, CorpsName) values (196, 'Aviation Logistics Corps');
insert into Corps (CorpsID, CorpsName) values (197, 'Special Operations Air Corps');
insert into Corps (CorpsID, CorpsName) values (198, 'Cyber Operations Corps');
insert into Corps (CorpsID, CorpsName) values (199, 'Advanced Training Corps');
insert into Corps (CorpsID, CorpsName) values (200, 'Tactical Equipment Support Corps');
insert into Corps (CorpsID, CorpsName) values (201, 'Medical Combat Support Corps');
insert into Corps (CorpsID, CorpsName) values (202, 'Strategic Equipment Corps');
insert into Corps (CorpsID, CorpsName) values (203, 'High-Altitude Operations Corps');
insert into Corps (CorpsID, CorpsName) values (204, 'Military Naval Research Corps');
insert into Corps (CorpsID, CorpsName) values (205, 'Psychological and Combat Support Corps');
insert into Corps (CorpsID, CorpsName) values (206, 'Heavy Armored Corps');
insert into Corps (CorpsID, CorpsName) values (207, 'Border Control Corps');
insert into Corps (CorpsID, CorpsName) values (208, 'Tactical Response Corps');
insert into Corps (CorpsID, CorpsName) values (209, 'Heavy Defense Corps');
insert into Corps (CorpsID, CorpsName) values (210, 'Advanced Communications Corps');
insert into Corps (CorpsID, CorpsName) values (211, 'Special Forces Support Corps');
insert into Corps (CorpsID, CorpsName) values (212, 'Military Health Corps');
insert into Corps (CorpsID, CorpsName) values (213, 'Crisis Management Corps');
insert into Corps (CorpsID, CorpsName) values (214, 'Military Air Support Corps');
insert into Corps (CorpsID, CorpsName) values (215, 'Tactical Combat Air Corps');
insert into Corps (CorpsID, CorpsName) values (216, 'Maritime Security Corps');
insert into Corps (CorpsID, CorpsName) values (217, 'Combat Engineering Response Corps');
insert into Corps (CorpsID, CorpsName) values (218, 'Military Mapping Support Corps');
insert into Corps (CorpsID, CorpsName) values (219, 'Tactical Air Rescue Corps');
insert into Corps (CorpsID, CorpsName) values (220, 'Security Forces Corps');
insert into Corps (CorpsID, CorpsName) values (221, 'Electronic Intelligence Corps');
insert into Corps (CorpsID, CorpsName) values (222, 'Military Legal Corps');
insert into Corps (CorpsID, CorpsName) values (223, 'Infantry Operations Corps');
insert into Corps (CorpsID, CorpsName) values (224, 'Special Forces Intelligence Corps');
insert into Corps (CorpsID, CorpsName) values (225, 'Battlefield Robotics Corps');
insert into Corps (CorpsID, CorpsName) values (226, 'Military Disaster Management Corps');
insert into Corps (CorpsID, CorpsName) values (227, 'Forward Observation Corps');
insert into Corps (CorpsID, CorpsName) values (228, 'Medical Operations Corps');
insert into Corps (CorpsID, CorpsName) values (229, 'Air Surveillance Corps');
insert into Corps (CorpsID, CorpsName) values (230, 'Electronic Defense Support Corps');
insert into Corps (CorpsID, CorpsName) values (231, 'Rapid Deployment Rescue Corps');
insert into Corps (CorpsID, CorpsName) values (232, 'Strategic Combat Intelligence Corps');
insert into Corps (CorpsID, CorpsName) values (233, 'Logistics and Transport Corps');
insert into Corps (CorpsID, CorpsName) values (234, 'Research and Development Corps');
insert into Corps (CorpsID, CorpsName) values (235, 'Air Combat Support Corps');
insert into Corps (CorpsID, CorpsName) values (236, 'Advanced Defense Corps');
insert into Corps (CorpsID, CorpsName) values (237, 'Joint Security Corps');
insert into Corps (CorpsID, CorpsName) values (238, 'Combat Support Medical Corps');
insert into Corps (CorpsID, CorpsName) values (239, 'Strategic Logistics Corps');
insert into Corps (CorpsID, CorpsName) values (240, 'Special Technology Corps');
insert into Corps (CorpsID, CorpsName) values (241, 'Operations and Strategy Corps');
insert into Corps (CorpsID, CorpsName) values (242, 'Medical Evacuation Support Corps');
insert into Corps (CorpsID, CorpsName) values (243, 'Tactical Engineering Corps');
insert into Corps (CorpsID, CorpsName) values (244, 'Airfield Security Corps');
insert into Corps (CorpsID, CorpsName) values (245, 'Battlefield Engineering Corps');
insert into Corps (CorpsID, CorpsName) values (246, 'Communications Support Corps');
insert into Corps (CorpsID, CorpsName) values (247, 'Counterterrorism Intelligence Corps');
insert into Corps (CorpsID, CorpsName) values (248, 'Infantry Corps');
insert into Corps (CorpsID, CorpsName) values (249, 'Armored Corps');
insert into Corps (CorpsID, CorpsName) values (250, 'Artillery Corps');
insert into Corps (CorpsID, CorpsName) values (251, 'Combat Intelligence Corps');
insert into Corps (CorpsID, CorpsName) values (252, 'Signal Corps');
insert into Corps (CorpsID, CorpsName) values (253, 'Engineering Corps');
insert into Corps (CorpsID, CorpsName) values (254, 'Medical Corps');
insert into Corps (CorpsID, CorpsName) values (255, 'Logistics Corps');
insert into Corps (CorpsID, CorpsName) values (256, 'Military Police Corps');
insert into Corps (CorpsID, CorpsName) values (257, 'Air Force');
insert into Corps (CorpsID, CorpsName) values (258, 'Navy');
insert into Corps (CorpsID, CorpsName) values (259, 'Cyber Warfare Corps');
insert into Corps (CorpsID, CorpsName) values (260, 'Reconnaissance Corps');
insert into Corps (CorpsID, CorpsName) values (261, 'Special Forces');
insert into Corps (CorpsID, CorpsName) values (262, 'Search and Rescue Corps');
insert into Corps (CorpsID, CorpsName) values (263, 'Intelligence Corps');
insert into Corps (CorpsID, CorpsName) values (264, 'Psychological Warfare Corps');
insert into Corps (CorpsID, CorpsName) values (265, 'Chemical Warfare Corps');
insert into Corps (CorpsID, CorpsName) values (266, 'Military Government Corps');
insert into Corps (CorpsID, CorpsName) values (267, 'Border Patrol Corps');
insert into Corps (CorpsID, CorpsName) values (268, 'Military Training Corps');
insert into Corps (CorpsID, CorpsName) values (269, 'Tactical Operations Corps');
insert into Corps (CorpsID, CorpsName) values (270, 'Communications Corps');
insert into Corps (CorpsID, CorpsName) values (271, 'Military Aviation Corps');
insert into Corps (CorpsID, CorpsName) values (272, 'Reserve Forces Corps');
insert into Corps (CorpsID, CorpsName) values (273, 'Equipment Maintenance Corps');
insert into Corps (CorpsID, CorpsName) values (274, 'Transport Corps');
insert into Corps (CorpsID, CorpsName) values (275, 'Military Intelligence Corps');
insert into Corps (CorpsID, CorpsName) values (276, 'Military Electronics Corps');
insert into Corps (CorpsID, CorpsName) values (277, 'Military Ordnance Corps');
insert into Corps (CorpsID, CorpsName) values (278, 'Military Engineering Corps');
insert into Corps (CorpsID, CorpsName) values (279, 'Heavy Equipment Corps');
insert into Corps (CorpsID, CorpsName) values (280, 'Infantry Special Operations Corps');
insert into Corps (CorpsID, CorpsName) values (281, 'Paratroopers Corps');
insert into Corps (CorpsID, CorpsName) values (282, 'Coastal Defense Corps');
insert into Corps (CorpsID, CorpsName) values (283, 'Missile Defense Corps');
insert into Corps (CorpsID, CorpsName) values (284, 'Army Radio Corps');
insert into Corps (CorpsID, CorpsName) values (285, 'Logistics and Supply Corps');
insert into Corps (CorpsID, CorpsName) values (286, 'Air Defense Corps');
insert into Corps (CorpsID, CorpsName) values (287, 'Technology and Innovation Corps');
insert into Corps (CorpsID, CorpsName) values (288, 'Defense Strategy Corps');
insert into Corps (CorpsID, CorpsName) values (289, 'Cyber Security Corps');
insert into Corps (CorpsID, CorpsName) values (290, 'Intelligence and Surveillance Corps');
insert into Corps (CorpsID, CorpsName) values (291, 'Rescue and Recovery Corps');
insert into Corps (CorpsID, CorpsName) values (292, 'Desert Warfare Corps');
insert into Corps (CorpsID, CorpsName) values (293, 'Maritime Warfare Corps');
insert into Corps (CorpsID, CorpsName) values (294, 'Combat Medical Corps');
insert into Corps (CorpsID, CorpsName) values (295, 'Psychological Operations Corps');
insert into Corps (CorpsID, CorpsName) values (296, 'Watercraft Corps');
insert into Corps (CorpsID, CorpsName) values (297, 'Command and Control Corps');
insert into Corps (CorpsID, CorpsName) values (298, 'Heavy Logistics Corps');
insert into Corps (CorpsID, CorpsName) values (299, 'Tactical Support Corps');
insert into Corps (CorpsID, CorpsName) values (300, 'Army Medical Research Corps');
insert into Corps (CorpsID, CorpsName) values (301, 'Urban Warfare Corps');
insert into Corps (CorpsID, CorpsName) values (302, 'Remote Sensing Corps');
insert into Corps (CorpsID, CorpsName) values (303, 'Special Reconnaissance Corps');
insert into Corps (CorpsID, CorpsName) values (304, 'Communications Intelligence Corps');
insert into Corps (CorpsID, CorpsName) values (305, 'Fire Support Corps');
insert into Corps (CorpsID, CorpsName) values (306, 'Military Sports Corps');
insert into Corps (CorpsID, CorpsName) values (307, 'Army Combat Training Corps');
insert into Corps (CorpsID, CorpsName) values (308, 'Medical Evacuation Corps');
insert into Corps (CorpsID, CorpsName) values (309, 'Field Engineers Corps');
insert into Corps (CorpsID, CorpsName) values (310, 'Field Artillery Corps');
insert into Corps (CorpsID, CorpsName) values (311, 'Military Communications Corps');
insert into Corps (CorpsID, CorpsName) values (312, 'Combat Support Corps');
insert into Corps (CorpsID, CorpsName) values (313, 'Firefighting Corps');
insert into Corps (CorpsID, CorpsName) values (314, 'Border Security Corps');
insert into Corps (CorpsID, CorpsName) values (315, 'Military Operations Corps');
insert into Corps (CorpsID, CorpsName) values (316, 'Electronic Warfare Corps');
insert into Corps (CorpsID, CorpsName) values (317, 'Naval Intelligence Corps');
insert into Corps (CorpsID, CorpsName) values (318, 'Special Air Service Corps');
insert into Corps (CorpsID, CorpsName) values (319, 'Armed Forces Band Corps');
insert into Corps (CorpsID, CorpsName) values (320, 'Light Infantry Corps');
insert into Corps (CorpsID, CorpsName) values (321, 'Heavy Infantry Corps');
insert into Corps (CorpsID, CorpsName) values (322, 'Military Science Corps');
insert into Corps (CorpsID, CorpsName) values (323, 'Logistics Support Corps');
insert into Corps (CorpsID, CorpsName) values (324, 'Coastal Patrol Corps');
insert into Corps (CorpsID, CorpsName) values (325, 'Advanced Warfare Corps');
insert into Corps (CorpsID, CorpsName) values (326, 'Tactical Rescue Corps');
insert into Corps (CorpsID, CorpsName) values (327, 'Engineering Support Corps');
insert into Corps (CorpsID, CorpsName) values (328, 'Army Aviation Corps');
insert into Corps (CorpsID, CorpsName) values (329, 'Heavy Transport Corps');
insert into Corps (CorpsID, CorpsName) values (330, 'Military Mapping Corps');
insert into Corps (CorpsID, CorpsName) values (331, 'Combat Logistics Corps');
insert into Corps (CorpsID, CorpsName) values (332, 'Army Maintenance Corps');
insert into Corps (CorpsID, CorpsName) values (333, 'Counterintelligence Corps');
insert into Corps (CorpsID, CorpsName) values (334, 'Military Construction Corps');
insert into Corps (CorpsID, CorpsName) values (335, 'Urban Security Corps');
insert into Corps (CorpsID, CorpsName) values (336, 'Crisis Response Corps');
insert into Corps (CorpsID, CorpsName) values (337, 'Special Weapons Corps');
insert into Corps (CorpsID, CorpsName) values (338, 'Combat Engineers Corps');
insert into Corps (CorpsID, CorpsName) values (339, 'Military Law Enforcement Corps');
insert into Corps (CorpsID, CorpsName) values (340, 'Strategic Command Corps');
insert into Corps (CorpsID, CorpsName) values (341, 'Joint Operations Corps');
insert into Corps (CorpsID, CorpsName) values (342, 'Cyber Defense Corps');
insert into Corps (CorpsID, CorpsName) values (343, 'Communication Networks Corps');
insert into Corps (CorpsID, CorpsName) values (344, 'Special Operations Forces');
insert into Corps (CorpsID, CorpsName) values (345, 'Airborne Corps');
insert into Corps (CorpsID, CorpsName) values (346, 'Military Aviation Maintenance Corps');
insert into Corps (CorpsID, CorpsName) values (347, 'Humanitarian Assistance Corps');
insert into Corps (CorpsID, CorpsName) values (348, 'Vehicle Repair Corps');
insert into Corps (CorpsID, CorpsName) values (349, 'Battlefield Surveillance Corps');
insert into Corps (CorpsID, CorpsName) values (350, 'Tactical Communications Corps');
insert into Corps (CorpsID, CorpsName) values (351, 'Specialized Infantry Corps');
insert into Corps (CorpsID, CorpsName) values (352, 'Logistics Planning Corps');
insert into Corps (CorpsID, CorpsName) values (353, 'Combat Aviation Corps');
insert into Corps (CorpsID, CorpsName) values (354, 'Military Simulation Corps');
insert into Corps (CorpsID, CorpsName) values (355, 'Rapid Deployment Corps');
insert into Corps (CorpsID, CorpsName) values (356, 'Military Research Corps');
insert into Corps (CorpsID, CorpsName) values (357, 'Border Defense Corps');
insert into Corps (CorpsID, CorpsName) values (358, 'Cyber Intelligence Corps');
insert into Corps (CorpsID, CorpsName) values (359, 'Advanced Electronics Corps');
insert into Corps (CorpsID, CorpsName) values (360, 'Security and Protection Corps');
insert into Corps (CorpsID, CorpsName) values (361, 'Air Transport Corps');
insert into Corps (CorpsID, CorpsName) values (362, 'Joint Combat Corps');
insert into Corps (CorpsID, CorpsName) values (363, 'Psychological Health Corps');
insert into Corps (CorpsID, CorpsName) values (364, 'Integrated Defense Corps');
insert into Corps (CorpsID, CorpsName) values (365, 'Tactical Communications Corps');
insert into Corps (CorpsID, CorpsName) values (366, 'Combat Engineering Support Corps');
insert into Corps (CorpsID, CorpsName) values (367, 'Army Medical Logistics Corps');
insert into Corps (CorpsID, CorpsName) values (368, 'Peacekeeping Operations Corps');
insert into Corps (CorpsID, CorpsName) values (369, 'Strategic Reconnaissance Corps');
insert into Corps (CorpsID, CorpsName) values (370, 'Tactical Supply Corps');
insert into Corps (CorpsID, CorpsName) values (371, 'Electronic Countermeasures Corps');
insert into Corps (CorpsID, CorpsName) values (372, 'Urban Combat Training Corps');
insert into Corps (CorpsID, CorpsName) values (373, 'Tank Battalion Corps');
insert into Corps (CorpsID, CorpsName) values (374, 'Military Psychological Health Corps');
insert into Corps (CorpsID, CorpsName) values (375, 'Humanitarian Logistics Corps');
insert into Corps (CorpsID, CorpsName) values (376, 'Technology Research Corps');
insert into Corps (CorpsID, CorpsName) values (377, 'Battlefield Communications Corps');
insert into Corps (CorpsID, CorpsName) values (378, 'Command Support Corps');
insert into Corps (CorpsID, CorpsName) values (379, 'Coastal Defense and Security Corps');
insert into Corps (CorpsID, CorpsName) values (380, 'Army Command Corps');
insert into Corps (CorpsID, CorpsName) values (381, 'Counterterrorism Corps');
insert into Corps (CorpsID, CorpsName) values (382, 'Heavy Weapons Corps');
insert into Corps (CorpsID, CorpsName) values (383, 'Strategic Airlift Corps');
insert into Corps (CorpsID, CorpsName) values (384, 'Electronic Surveillance Corps');
insert into Corps (CorpsID, CorpsName) values (385, 'Chemical and Biological Defense Corps');
insert into Corps (CorpsID, CorpsName) values (386, 'Advanced Weaponry Corps');
insert into Corps (CorpsID, CorpsName) values (387, 'Military Security Corps');
insert into Corps (CorpsID, CorpsName) values (388, 'Ammunition Support Corps');
insert into Corps (CorpsID, CorpsName) values (389, 'Logistics Engineering Corps');
insert into Corps (CorpsID, CorpsName) values (390, 'Remote Operations Corps');
insert into Corps (CorpsID, CorpsName) values (391, 'Medical Research Corps');
insert into Corps (CorpsID, CorpsName) values (392, 'Counter-Terror Operations Corps');
insert into Corps (CorpsID, CorpsName) values (393, 'Combat Health Corps');
insert into Corps (CorpsID, CorpsName) values (394, 'Military Hazardous Materials Corps');
insert into Corps (CorpsID, CorpsName) values (395, 'Search and Rescue Support Corps');
insert into Corps (CorpsID, CorpsName) values (396, 'CBRN Defense Corps');
insert into Corps (CorpsID, CorpsName) values (397, 'Tactical Air Support Corps');
insert into Corps (CorpsID, CorpsName) values (398, 'Cyber Research Corps');
insert into Corps (CorpsID, CorpsName) values (399, 'Amphibious Warfare Corps');
insert into Corps (CorpsID, CorpsName) values (400, 'Cyber Warfare Support Corps');
