insert into MOCK_DATA (CropsID, CropsName, Specialization) values (1, 'Oketz Unit', 'Equipment Delivery');
insert into MOCK_DATA (CropsID, CropsName, Specialization) values (2, 'Military Rabbinate', 'High-Alert Command');
insert into MOCK_DATA (CropsID, CropsName, Specialization) values (3, 'Bahad 21', 'Cyber Tactics');
insert into MOCK_DATA (CropsID, CropsName, Specialization) values (4, 'Combat Engineering Corps', 'Ballistic Defense');
insert into MOCK_DATA (CropsID, CropsName, Specialization) values (5, 'Bahad 72', 'Tactical Supply Drops');
insert into MOCK_DATA (CropsID, CropsName, Specialization) values (6, 'Missile Command Unit', 'Commando Infiltration');
insert into MOCK_DATA (CropsID, CropsName, Specialization) values (7, 'Data Security Department', 'Command Doctrine');
insert into MOCK_DATA (CropsID, CropsName, Specialization) values (8, 'Bahad 64', 'Anti-Air Support');
insert into MOCK_DATA (CropsID, CropsName, Specialization) values (9, 'Bahad 89', 'Draft Planning');
insert into MOCK_DATA (CropsID, CropsName, Specialization) values (10, 'Cyber Warfare Command', 'Air Photo Interpretation');
insert into MOCK_DATA (CropsID, CropsName, Specialization) values (11, 'Sea Corps Base', 'Doctrine Development');
insert into MOCK_DATA (CropsID, CropsName, Specialization) values (12, 'Space Administration', 'Combat Preparation');
insert into MOCK_DATA (CropsID, CropsName, Specialization) values (13, 'Command & Control Center', 'Remote Medicine');
insert into MOCK_DATA (CropsID, CropsName, Specialization) values (14, 'Sayeret Matkal', 'Intelligence Briefing');
insert into MOCK_DATA (CropsID, CropsName, Specialization) values (15, 'Reserve Administration', 'Vocal Performance');
insert into MOCK_DATA (CropsID, CropsName, Specialization) values (16, 'Naval Instruction School', 'Long-Term Planning');
insert into MOCK_DATA (CropsID, CropsName, Specialization) values (17, 'Bahad 91', 'Explosive Disposal');
insert into MOCK_DATA (CropsID, CropsName, Specialization) values (18, 'Bahad 8', 'Explosive Disposal');
insert into MOCK_DATA (CropsID, CropsName, Specialization) values (19, 'Airborne Assault Unit', 'Recon Training');
insert into MOCK_DATA (CropsID, CropsName, Specialization) values (20, 'Home Front Rescue Brigade', 'Educational Program Development');
insert into MOCK_DATA (CropsID, CropsName, Specialization) values (21, 'Bahad 63', 'Explosive Disposal');
insert into MOCK_DATA (CropsID, CropsName, Specialization) values (22, 'Bahad 62', 'Info Warfare Doctrine');
insert into MOCK_DATA (CropsID, CropsName, Specialization) values (23, 'Canine Unit', 'Tank Command');
insert into MOCK_DATA (CropsID, CropsName, Specialization) values (24, 'Bahad 43', 'Rocket Targeting');
insert into MOCK_DATA (CropsID, CropsName, Specialization) values (25, 'Naval Instruction School', 'Refresher Combat Training.');
insert into MOCK_DATA (CropsID, CropsName, Specialization) values (26, 'Bahad 14', 'Guerrilla Warfare');
insert into MOCK_DATA (CropsID, CropsName, Specialization) values (27, 'Satellite Intelligence Unit', 'Special Operations');
insert into MOCK_DATA (CropsID, CropsName, Specialization) values (28, 'Field Observers Unit', 'Military Law');
insert into MOCK_DATA (CropsID, CropsName, Specialization) values (29, 'Armored School', 'Communications Design');
insert into MOCK_DATA (CropsID, CropsName, Specialization) values (30, 'Bahad 4', 'Jungle Warfare');
insert into MOCK_DATA (CropsID, CropsName, Specialization) values (31, 'Bahad 33', 'Cyber Defense');
insert into MOCK_DATA (CropsID, CropsName, Specialization) values (32, 'Operational Medicine Unit', 'Target Acquisition');
insert into MOCK_DATA (CropsID, CropsName, Specialization) values (33, 'Bahad 99', 'Supply Planning');
insert into MOCK_DATA (CropsID, CropsName, Specialization) values (34, 'Shayetet 13', 'Satellite Imaging');
insert into MOCK_DATA (CropsID, CropsName, Specialization) values (35, 'Drone Command', 'Communications Tower Setup');
insert into MOCK_DATA (CropsID, CropsName, Specialization) values (36, 'Dog Training School', 'Firefighting Rescue');
insert into MOCK_DATA (CropsID, CropsName, Specialization) values (37, 'Shayetet 13', 'Combat Sim Strategy');
insert into MOCK_DATA (CropsID, CropsName, Specialization) values (38, 'Technology and Maintenance Corps', 'Naval Assault');
insert into MOCK_DATA (CropsID, CropsName, Specialization) values (39, 'Southern Engineering Battalion', 'Recon Training');
insert into MOCK_DATA (CropsID, CropsName, Specialization) values (40, 'Bahad 34', 'Hazardous Material Response');
